### ISSUE TITLE
Unable to get backend for files_external_dropbox

### ISSUE THREAD

**Issue by ChrisScrumping** [icewind1991/files_external_dropbox#11]
After install I am getting a lot of error messages in the UI saying: 
Error | files_external | Could not load storage: "Unable to get backend for files_external_dropbox"

I am assuming is a permission issue somewhere?

Only way to stop the error is to disable the external storage app - even tho I have disabled and removed the external storage dropbox app already.

Any suggestions on stopping the error message?

**Comment by ChrisScrumping** [comment]
So I have re-enabled the files_external_dropbox app and seems I did not remove the dropbox connection I made properly (I thought I had) once removed this stops the errors!

As soon as I try and connected to dropbox the error returns "Unable to get backend for files_external_dropbox" 

As I say I assume its a permissions issue but not sure any suggestions on where I could start looking would be appreciated - the nextcloud.log file does not seem to give anything more useful than the UI.

**Comment by Jonthe838** [comment]
I'm getting the same error as mentioned above, 1-2 times per second. But I do also get the following which i presume is related to the issue mentioned above.

````
Exception: Creating \OCA\Files_external_dropbox\Storage\Dropbox storage failed
/var/www/mydomain.com/public_html/nxcl/apps/files_external/lib/config.php - line 230: OCA\Files_external_dropbox\Storage\Dropbox->__construct(Array)
/var/www/mydomain.com/public_html/nxcl/apps/files_external/lib/Controller/StoragesController.php - line 256: OC_Mount_Config getBackendStatus('\\OCA\\Files_exte...', Array, false, true)
/var/www/mydomain.com/public_html/nxcl/apps/files_external/lib/Controller/StoragesController.php - line 305: OCA\Files_External\Controller\StoragesController->updateStorageStatus(Object(OCA\Files_External\Lib\StorageConfig), true)
[internal function] OCA\Files_External\Controller\StoragesController->show(5, true)
/var/www/mydomain.com/public_html/nxcl/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
/var/www/mydomain.com/public_html/nxcl/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Files_External\Controller\GlobalStoragesController), 'show')
/var/www/mydomain.com/public_html/nxcl/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Files_External\Controller\GlobalStoragesController), 'show')
/var/www/mydomain.com/public_html/nxcl/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\Files_Exter...', 'show', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/var/www/mydomain.com/public_html/nxcl/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/var/www/mydomain.com/public_html/nxcl/lib/base.php - line 1004: OC\Route\Router->match('/apps/files_ext...')
/var/www/mydomain.com/public_html/nxcl/index.php - line 48: OC handleRequest()
{main}
````

**Comment by devjb** [comment]
Is there anything else we can provide to help you looking into this issue?

**Comment by icewind1991** [comment]
Can you check if the `files_external_dropbox` app stays enabled when trying to access the dropbox folder.
The error message makes it seems like the app gets disabled because an error is detected.

You can list installed apps by `occ app:list`

**Comment by mTrax-** [comment]
Hello,
I have exactly the same problem associated to this problem (https://github.com/icewind1991/files_external_dropbox/issues/14)
When I try to enter the dropbox folder, nothing happens until nginx timeout and it displays my nextcloud homepage.

I have these two error messages spamming my log file : 
{"reqId":"HVqOhDLFhGGypYrOCjUy","level":3,"time":"2017-12-22T15:44:55-05:00","remoteAddr":"192.168.xxx","user":"xxx","app":"files_external","method":"PROPFIND","url":"\/remote.php\/dav\/files\/xxx\/","message":"Could not load storage: \"Unable to get backend for files_external_dropbox\"","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.1 (build 8) (Nextcloud)","version":"12.0.4.3"}
{"reqId":"5mNkNxZ8ADLD8BnvlUMO","level":3,"time":"2017-12-22T15:45:09-05:00","remoteAddr":"192.168.xxx","user":"xxx","app":"files_external","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v2\/notifications","message":"Could not load storage: \"Unable to get backend for files_external_dropbox\"","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}

I am using nginx / php-fpm / APCu and Redis.

Hope it can help.

**Comment by GAS85** [comment]
It is also happen with me, as additional I'm suffering from 100% CPU usage by mysql since update.

**Comment by garzy** [comment]
Same problem, I can't avoid these same error, I'm trying some ways buf unsuccesfull :(, please fix this soon. Thanks!

**Comment by devjb** [comment]
With the latest master the sync itself is working now for root and all sub folders. But I still have the well known error message flooding my logs. 

I set up the external dropbox with a new folder name to sync to but the problem persists. 

I noticed two different error messages (exceptions) right after setting up a fresh dropbox storage:

{"reqId":"0LmfJFI4chccoiIa8V9Y","level":3,"time":"2018-01-15T21:06:48+01:00","remoteAddr":"13.37.13.37","user":"johndoe","app":"files_external","method":"POST","url":"\/nextcloud\/apps\/files_external\/globalstorages","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Creating \\\\OCA\\\\Files_external_dropbox\\\\Storage\\\\Dropbox storage failed\",\"Code\":0,\"Trace\":\"#0 \\\/server-path\\\/nextcloud\\\/apps\\\/files_external\\\/lib\\\/config.php(230): OCA\\\\Files_external_dropbox\\\\Storage\\\\Dropbox->__construct(Array)\\n#1 \\\/server-path\\\/nextcloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/StoragesController.php(257): OC_Mount_Config::getBackendStatus('\\\\\\\\OCA\\\\\\\\Files_exte...', Array, false, true)\\n#2 \\\/server-path\\\/nextcloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/GlobalStoragesController.php(112): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OCA\\\\Files_External\\\\Lib\\\\StorageConfig))\\n#3 [internal function]: OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController->create('DropboxV2', 'files_external_...', 'oauth2::oauth2', Array, Array, Array, Array, 100)\\n#4 \\\/server-path\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#5 \\\/server-path\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'create')\\n#6 \\\/server-path\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'create')\\n#7 \\\/server-path\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('GlobalStoragesC...', 'create', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#8 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#9 \\\/server-path\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#10 \\\/server-path\\\/nextcloud\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#11 \\\/server-path\\\/nextcloud\\\/index.php(48): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/server-path\\\/nextcloud\\\/apps\\\/files_external_dropbox\\\/lib\\\/Storage\\\/Dropbox.php\",\"Line\":106}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}


{"reqId":"ZK1fK3qH39LxyeGPoBLq","level":3,"time":"2018-01-15T21:06:49+01:00","remoteAddr":"13.37.13.37","user":"johndoe","app":"files_external","method":"GET","url":"\/nextcloud\/apps\/files_external\/globalstorages\/4?testOnly=true","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Creating \\\\OCA\\\\Files_external_dropbox\\\\Storage\\\\Dropbox storage failed\",\"Code\":0,\"Trace\":\"#0 \\\/server-path\\\/nextcloud\\\/apps\\\/files_external\\\/lib\\\/config.php(230): OCA\\\\Files_external_dropbox\\\\Storage\\\\Dropbox->__construct(Array)\\n#1 \\\/server-path\\\/nextcloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/StoragesController.php(257): OC_Mount_Config::getBackendStatus('\\\\\\\\OCA\\\\\\\\Files_exte...', Array, false, true)\\n#2 \\\/server-path\\\/nextcloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/StoragesController.php(305): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OCA\\\\Files_External\\\\Lib\\\\StorageConfig), true)\\n#3 [internal function]: OCA\\\\Files_External\\\\Controller\\\\StoragesController->show(4, true)\\n#4 \\\/server-path\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#5 \\\/server-path\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'show')\\n#6 \\\/server-path\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'show')\\n#7 \\\/server-path\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('GlobalStoragesC...', 'show', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#8 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#9 \\\/server-path\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#10 \\\/server-path\\\/nextcloud\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#11 \\\/server-path\\\/nextcloud\\\/index.php(48): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/server-path\\\/nextcloud\\\/apps\\\/files_external_dropbox\\\/lib\\\/Storage\\\/Dropbox.php\",\"Line\":106}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}

**Comment by devjb** [comment]
After the upgrade to NC13 today, the flooding errors disappeared. Great!

The above two errors are still present though. Should I create a new issue for them?

**Comment by bcutter** [comment]
Same here since migrated to NC v12.0.5. Waiting for NC v13.0.1 to get it fixed.
